name: Deploy to Google Cloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Deploy Backend (Node.js)
        run: |
          gcloud config set project YOUR_PROJECT_ID
          gcloud app deploy backend/app.yaml --quiet

      - name: Build & Deploy Frontend (React)
        run: |
          cd frontend
          npm install
          npm run build
          gsutil -m rsync -r build gs://YOUR_BUCKET_NAME
